<?php
namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;


/**
 * FlavoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlavoursRepository extends EntityRepository
{
    public function findByid()
    {
        $entityManager = $this->getEntityManager();
        $query=$entityManager->createQuery('Flavours')
            ->leftJoin('Flavours.OrdersFlavours', 'OrdersFlavours')
           ->getQuery()
            ->execute();

}

}
