<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * OrdersToppingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersToppingsRepository extends EntityRepository
{
}
