<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * OrdersFlavoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersFlavoursRepository extends EntityRepository
{
}
